# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'between_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_in_item_Main(object):
    def setupUi(self, in_item_Main):
        in_item_Main.setObjectName("in_item_Main")
        in_item_Main.resize(317, 43)
        self.horizontalLayout = QtWidgets.QHBoxLayout(in_item_Main)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_btn = MPushButton(in_item_Main)
        self.edit_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.edit_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.edit_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_additionalActions.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_additionalActions_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_additionalActions_light.png);\n"
"}\n"
"")
        self.edit_btn.setText("")
        self.edit_btn.setObjectName("edit_btn")
        self.horizontalLayout.addWidget(self.edit_btn)
        spacerItem = QtWidgets.QSpacerItem(4, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.val_le = MLineEdit(in_item_Main)
        self.val_le.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.val_le.setFont(font)
        self.val_le.setObjectName("val_le")
        self.horizontalLayout.addWidget(self.val_le)
        self.val_slider = MSlider(in_item_Main)
        self.val_slider.setMaximum(100)
        self.val_slider.setOrientation(QtCore.Qt.Horizontal)
        self.val_slider.setObjectName("val_slider")
        self.horizontalLayout.addWidget(self.val_slider)
        self.set_btn = MPushButton(in_item_Main)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.set_btn.setFont(font)
        self.set_btn.setObjectName("set_btn")
        self.horizontalLayout.addWidget(self.set_btn)
        self.delete_btn = QtWidgets.QPushButton(in_item_Main)
        self.delete_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.delete_btn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_keyDeleteAll.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_keyDeleteAll_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_keyDeleteAll_light.png);\n"
"}\n"
"")
        self.delete_btn.setText("")
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout.addWidget(self.delete_btn)

        self.retranslateUi(in_item_Main)
        QtCore.QMetaObject.connectSlotsByName(in_item_Main)

    def retranslateUi(self, in_item_Main):
        _translate = QtCore.QCoreApplication.translate
        in_item_Main.setWindowTitle(_translate("in_item_Main", "Form"))
        self.val_le.setText(_translate("in_item_Main", "0.00"))
        self.set_btn.setText(_translate("in_item_Main", "Set"))
from dayu_widgets.line_edit import MLineEdit
from dayu_widgets.push_button import MPushButton
from dayu_widgets.slider import MSlider
from dayu_widgets.static import icon_rc


