# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BS_List.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_BS_ListMain(object):
    def setupUi(self, BS_ListMain):
        BS_ListMain.setObjectName("BS_ListMain")
        BS_ListMain.resize(317, 624)
        self.verticalLayout = QtWidgets.QVBoxLayout(BS_ListMain)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.load_hb = QtWidgets.QHBoxLayout()
        self.load_hb.setObjectName("load_hb")
        self.load_btn = MPushButton()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.load_btn.setFont(font)
        self.load_btn.setObjectName("load_btn")
        self.load_hb.addWidget(self.load_btn)
        self.load_le = MLineEdit()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.load_le.setFont(font)
        self.load_le.setObjectName("load_le")
        self.load_hb.addWidget(self.load_le)
        self.setting_btn = QtWidgets.QPushButton(BS_ListMain)
        self.setting_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.setting_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.setting_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_preferences_150.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_preferences_150_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_preferences_150_light.png);\n"
"}")
        self.setting_btn.setText("")
        self.setting_btn.setObjectName("setting_btn")
        self.load_hb.addWidget(self.setting_btn)
        self.verticalLayout.addLayout(self.load_hb)
        self.bs_hb = QtWidgets.QHBoxLayout()
        self.bs_hb.setObjectName("bs_hb")
        self.bs_lb = MLabel()
        self.bs_lb.setMinimumSize(QtCore.QSize(0, 0))
        self.bs_lb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.bs_lb.setFont(font)
        self.bs_lb.setObjectName("bs_lb")
        self.bs_hb.addWidget(self.bs_lb)
        self.bs_cb = MComboBox()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.bs_cb.setFont(font)
        self.bs_cb.setObjectName("bs_cb")
        self.bs_cb.addItem("")
        self.bs_hb.addWidget(self.bs_cb)
        self.verticalLayout.addLayout(self.bs_hb)
        self.target_lb = MLabel()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.target_lb.setFont(font)
        self.target_lb.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.target_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.target_lb.setObjectName("target_lb")
        self.verticalLayout.addWidget(self.target_lb)
        self.search_le = MLineEdit()
        self.search_le.setObjectName("search_le")
        self.verticalLayout.addWidget(self.search_le)
        self.target_list = QtWidgets.QListWidget(BS_ListMain)
        self.target_list.setObjectName("target_list")
        self.verticalLayout.addWidget(self.target_list)
        self.edit_hb = QtWidgets.QHBoxLayout()
        self.edit_hb.setSpacing(2)
        self.edit_hb.setObjectName("edit_hb")
        self.edit_btn = MPushButton()
        self.edit_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.edit_btn.setFont(font)
        self.edit_btn.setStyleSheet("")
        self.edit_btn.setObjectName("edit_btn")
        self.edit_hb.addWidget(self.edit_btn)
        spacerItem = QtWidgets.QSpacerItem(80, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.edit_hb.addItem(spacerItem)
        self.ccs_btn = QtWidgets.QPushButton(BS_ListMain)
        self.ccs_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.ccs_btn.setMaximumSize(QtCore.QSize(10, 20))
        self.ccs_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_comboMembers_200.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_comboMembers_200_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_comboMembers_200_light.png);\n"
"}")
        self.ccs_btn.setText("")
        self.ccs_btn.setObjectName("ccs_btn")
        self.edit_hb.addWidget(self.ccs_btn)
        self.dup_btn = QtWidgets.QPushButton(BS_ListMain)
        self.dup_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.dup_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.dup_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_weightPaste_200.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_weightPaste_200_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_weightPaste_200_light.png);\n"
"}")
        self.dup_btn.setText("")
        self.dup_btn.setObjectName("dup_btn")
        self.edit_hb.addWidget(self.dup_btn)
        self.extr_btn = QtWidgets.QPushButton(BS_ListMain)
        self.extr_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.extr_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.extr_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_weightExport_200.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_weightExport_200_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_weightExport_200_light.png);\n"
"}")
        self.extr_btn.setText("")
        self.extr_btn.setObjectName("extr_btn")
        self.edit_hb.addWidget(self.extr_btn)
        self.verticalLayout.addLayout(self.edit_hb)
        self.inbetween_list = QtWidgets.QListWidget(BS_ListMain)
        self.inbetween_list.setMaximumSize(QtCore.QSize(16777215, 40))
        self.inbetween_list.setObjectName("inbetween_list")
        self.verticalLayout.addWidget(self.inbetween_list)
        self.mirror_vb = QtWidgets.QVBoxLayout()
        self.mirror_vb.setObjectName("mirror_vb")
        self.mirror_lb = MLabel()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.mirror_lb.setFont(font)
        self.mirror_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.mirror_lb.setObjectName("mirror_lb")
        self.mirror_vb.addWidget(self.mirror_lb)
        self.axis_hb = QtWidgets.QHBoxLayout()
        self.axis_hb.setObjectName("axis_hb")
        self.axis_lb = MLabel()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.axis_lb.setFont(font)
        self.axis_lb.setObjectName("axis_lb")
        self.axis_hb.addWidget(self.axis_lb)
        self.x_rb = MRadioButton()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.x_rb.setFont(font)
        self.x_rb.setObjectName("x_rb")
        self.axis_hb.addWidget(self.x_rb)
        self.y_rb = MRadioButton()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.y_rb.setFont(font)
        self.y_rb.setChecked(True)
        self.y_rb.setObjectName("y_rb")
        self.axis_hb.addWidget(self.y_rb)
        self.z_rb = MRadioButton()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.z_rb.setFont(font)
        self.z_rb.setObjectName("z_rb")
        self.axis_hb.addWidget(self.z_rb)
        self.mirror_vb.addLayout(self.axis_hb)
        self.name_hb = QtWidgets.QHBoxLayout()
        self.name_hb.setObjectName("name_hb")
        self.name_lb = MLabel()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.name_lb.setFont(font)
        self.name_lb.setObjectName("name_lb")
        self.name_hb.addWidget(self.name_lb)
        self.name_le = MLineEdit()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.name_le.setFont(font)
        self.name_le.setObjectName("name_le")
        self.name_hb.addWidget(self.name_le)
        self.mirror_vb.addLayout(self.name_hb)
        self.mirror_btn = MPushButton()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.mirror_btn.setFont(font)
        self.mirror_btn.setObjectName("mirror_btn")
        self.mirror_vb.addWidget(self.mirror_btn)
        self.verticalLayout.addLayout(self.mirror_vb)

        self.retranslateUi(BS_ListMain)
        QtCore.QMetaObject.connectSlotsByName(BS_ListMain)

    def retranslateUi(self, BS_ListMain):
        _translate = QtCore.QCoreApplication.translate
        BS_ListMain.setWindowTitle(_translate("BS_ListMain", "Form"))
        self.load_btn.setToolTip(_translate("BS_ListMain", "Load mesh"))
        self.load_btn.setText(_translate("BS_ListMain", "Load"))
        self.load_le.setPlaceholderText(_translate("BS_ListMain", "Load one mesh with BS"))
        self.setting_btn.setToolTip(_translate("BS_ListMain", "Settings"))
        self.bs_lb.setText(_translate("BS_ListMain", "BS Name"))
        self.bs_cb.setItemText(0, _translate("BS_ListMain", "None"))
        self.target_lb.setText(_translate("BS_ListMain", "BlendShape Target List "))
        self.edit_btn.setToolTip(_translate("BS_ListMain", "Crate new blendShape"))
        self.edit_btn.setText(_translate("BS_ListMain", "Create Target"))
        self.ccs_btn.setToolTip(_translate("BS_ListMain", "Create Correct Shape"))
        self.dup_btn.setToolTip(_translate("BS_ListMain", "Duplicate mesh"))
        self.extr_btn.setToolTip(_translate("BS_ListMain", "Extract target"))
        self.mirror_lb.setText(_translate("BS_ListMain", "Mirror Target"))
        self.axis_lb.setText(_translate("BS_ListMain", "Axis"))
        self.x_rb.setText(_translate("BS_ListMain", "X"))
        self.y_rb.setText(_translate("BS_ListMain", "Y"))
        self.z_rb.setText(_translate("BS_ListMain", "Z"))
        self.name_lb.setText(_translate("BS_ListMain", "Name Of Copy"))
        self.name_le.setPlaceholderText(_translate("BS_ListMain", "Mirror Name Of Shape"))
        self.mirror_btn.setText(_translate("BS_ListMain", "Mirror Target"))
from dayu_widgets.combo_box import MComboBox
from dayu_widgets.label import MLabel
from dayu_widgets.line_edit import MLineEdit
from dayu_widgets.push_button import MPushButton
from dayu_widgets.radio_button import MRadioButton
from dayu_widgets.static import icon_rc
