# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Code\Faith_Proj\Faith\Tools\BS_Manager\UI\between_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_in_item_Main(object):
    def setupUi(self, in_item_Main):
        in_item_Main.setObjectName("in_item_Main")
        in_item_Main.resize(372, 43)
        self.horizontalLayout = QtWidgets.QHBoxLayout(in_item_Main)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.base_lb = MLabel(in_item_Main)
        self.base_lb.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(False)
        font.setWeight(50)
        self.base_lb.setFont(font)
        self.base_lb.setObjectName("base_lb")
        self.horizontalLayout.addWidget(self.base_lb)
        self.val_dspin = MDoubleSpinBox (in_item_Main)
        self.val_dspin.setMinimumSize(QtCore.QSize(40, 0))
        self.val_dspin.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.val_dspin.setDecimals(3)
        self.val_dspin.setMaximum(1.0)
        self.val_dspin.setSingleStep(0.001)
        self.val_dspin.setObjectName("val_dspin")
        self.horizontalLayout.addWidget(self.val_dspin)
        self.val_slider = MSlider(in_item_Main)
        self.val_slider.setMaximum(1000)
        self.val_slider.setOrientation(QtCore.Qt.Horizontal)
        self.val_slider.setObjectName("val_slider")
        self.horizontalLayout.addWidget(self.val_slider)
        self.delete_btn = QtWidgets.QPushButton(in_item_Main)
        self.delete_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.delete_btn.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_keyDeleteAll.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_keyDeleteAll_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_keyDeleteAll_light.png);\n"
"}\n"
"")
        self.delete_btn.setText("")
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout.addWidget(self.delete_btn)

        self.retranslateUi(in_item_Main)
        QtCore.QMetaObject.connectSlotsByName(in_item_Main)

    def retranslateUi(self, in_item_Main):
        _translate = QtCore.QCoreApplication.translate
        in_item_Main.setWindowTitle(_translate("in_item_Main", "Form"))
        self.base_lb.setText(_translate("in_item_Main", "数值"))
        self.delete_btn.setToolTip(_translate("in_item_Main", "删除"))
from dayu_widgets.label import MLabel
from dayu_widgets.slider import MSlider
from dayu_widgets.spin_box import MDoubleSpinBox 
import icon_rc
