# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Code\Faith_Proj\Faith\Tools\BS_Manager\UI\BS_clone.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Clone_Main(object):
    def setupUi(self, Clone_Main):
        Clone_Main.setObjectName("Clone_Main")
        Clone_Main.resize(317, 537)
        self.verticalLayout = QtWidgets.QVBoxLayout(Clone_Main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.load_widget = QtWidgets.QWidget(Clone_Main)
        self.load_widget.setObjectName("load_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.load_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.source_hb = QtWidgets.QHBoxLayout()
        self.source_hb.setObjectName("source_hb")
        self.source_btn = MPushButton(self.load_widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.source_btn.setFont(font)
        self.source_btn.setObjectName("source_btn")
        self.source_hb.addWidget(self.source_btn)
        self.source_le = MLineEdit(self.load_widget)
        self.source_le.setEnabled(False)
        self.source_le.setObjectName("source_le")
        self.source_hb.addWidget(self.source_le)
        self.verticalLayout_2.addLayout(self.source_hb)
        self.target_hb = QtWidgets.QHBoxLayout()
        self.target_hb.setObjectName("target_hb")
        self.target_btn = MPushButton(self.load_widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.target_btn.setFont(font)
        self.target_btn.setObjectName("target_btn")
        self.target_hb.addWidget(self.target_btn)
        self.target_le = MLineEdit(self.load_widget)
        self.target_le.setEnabled(False)
        self.target_le.setObjectName("target_le")
        self.target_hb.addWidget(self.target_le)
        self.verticalLayout_2.addLayout(self.target_hb)
        self.bs_hb = QtWidgets.QHBoxLayout()
        self.bs_hb.setObjectName("bs_hb")
        self.bs_lb = MLabel(self.load_widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.bs_lb.setFont(font)
        self.bs_lb.setObjectName("bs_lb")
        self.bs_hb.addWidget(self.bs_lb)
        self.bs_combo = MComboBox(self.load_widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.bs_combo.setFont(font)
        self.bs_combo.setObjectName("bs_combo")
        self.bs_combo.addItem("")
        self.bs_hb.addWidget(self.bs_combo)
        self.verticalLayout_2.addLayout(self.bs_hb)
        self.refresh_btn = MPushButton(self.load_widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(False)
        font.setWeight(50)
        self.refresh_btn.setFont(font)
        self.refresh_btn.setObjectName("refresh_btn")
        self.verticalLayout_2.addWidget(self.refresh_btn)
        self.verticalLayout.addWidget(self.load_widget)
        self.cloneList_widget = QtWidgets.QWidget(Clone_Main)
        self.cloneList_widget.setObjectName("cloneList_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cloneList_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.search_le = MLineEdit(self.cloneList_widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.search_le.setFont(font)
        self.search_le.setObjectName("search_le")
        self.verticalLayout_3.addWidget(self.search_le)
        self.item_list = QtWidgets.QListWidget(self.cloneList_widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.item_list.setFont(font)
        self.item_list.setObjectName("item_list")
        self.verticalLayout_3.addWidget(self.item_list)
        self.clone_btn = MPushButton(self.cloneList_widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.clone_btn.setFont(font)
        self.clone_btn.setObjectName("clone_btn")
        self.verticalLayout_3.addWidget(self.clone_btn)
        self.verticalLayout.addWidget(self.cloneList_widget)

        self.retranslateUi(Clone_Main)
        QtCore.QMetaObject.connectSlotsByName(Clone_Main)

    def retranslateUi(self, Clone_Main):
        _translate = QtCore.QCoreApplication.translate
        Clone_Main.setWindowTitle(_translate("Clone_Main", "Form"))
        self.source_btn.setText(_translate("Clone_Main", "加载拷贝模型"))
        self.target_btn.setText(_translate("Clone_Main", "加载目标模型"))
        self.bs_lb.setText(_translate("Clone_Main", "BS 名称"))
        self.bs_combo.setItemText(0, _translate("Clone_Main", "None"))
        self.refresh_btn.setText(_translate("Clone_Main", "刷新列表"))
        self.item_list.setSortingEnabled(False)
        self.clone_btn.setText(_translate("Clone_Main", "拷贝"))
from dayu_widgets.combo_box import MComboBox
from dayu_widgets.label import MLabel
from dayu_widgets.line_edit import MLineEdit
from dayu_widgets.push_button import MPushButton
