# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Code\Faith_Proj\Faith\Tools\BS_Manager\UI\driver_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_driveItem_Main(object):
    def setupUi(self, driveItem_Main):
        driveItem_Main.setObjectName("driveItem_Main")
        driveItem_Main.resize(296, 39)
        self.horizontalLayout = QtWidgets.QHBoxLayout(driveItem_Main)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.driver_lb = MLabel(driveItem_Main)
        self.driver_lb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.driver_lb.setFont(font)
        self.driver_lb.setObjectName("driver_lb")
        self.horizontalLayout.addWidget(self.driver_lb)
        self.rx_le = MLineEdit(driveItem_Main)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.rx_le.setFont(font)
        self.rx_le.setObjectName("rx_le")
        self.horizontalLayout.addWidget(self.rx_le)
        self.ry_le = MLineEdit(driveItem_Main)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.ry_le.setFont(font)
        self.ry_le.setObjectName("ry_le")
        self.horizontalLayout.addWidget(self.ry_le)
        self.rz_le = MLineEdit(driveItem_Main)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.rz_le.setFont(font)
        self.rz_le.setObjectName("rz_le")
        self.horizontalLayout.addWidget(self.rz_le)
        self.set_btn = QtWidgets.QPushButton(driveItem_Main)
        self.set_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.set_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.set_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_btn_locator_150.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_btn_locator_150_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_btn_locator_150_light.png);\n"
"}")
        self.set_btn.setText("")
        self.set_btn.setObjectName("set_btn")
        self.horizontalLayout.addWidget(self.set_btn)

        self.retranslateUi(driveItem_Main)
        QtCore.QMetaObject.connectSlotsByName(driveItem_Main)

    def retranslateUi(self, driveItem_Main):
        _translate = QtCore.QCoreApplication.translate
        driveItem_Main.setWindowTitle(_translate("driveItem_Main", "Form"))
        self.driver_lb.setText(_translate("driveItem_Main", "Up Driver"))
        self.rx_le.setText(_translate("driveItem_Main", "0.000"))
        self.ry_le.setText(_translate("driveItem_Main", "0.000"))
        self.rz_le.setText(_translate("driveItem_Main", "0.000"))
        self.set_btn.setToolTip(_translate("driveItem_Main", "设置"))
from dayu_widgets.label import MLabel
from dayu_widgets.line_edit import MLineEdit
import icon_rc
