# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Code\Faith_Proj\Faith\Tools\BS_Manager\UI\list_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_listItem_Main(object):
    def setupUi(self, listItem_Main):
        listItem_Main.setObjectName("listItem_Main")
        listItem_Main.resize(438, 43)
        self.horizontalLayout = QtWidgets.QHBoxLayout(listItem_Main)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connect_btn = MPushButton(listItem_Main)
        self.connect_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.connect_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.connect_btn.setStyleSheet("")
        self.connect_btn.setText("")
        self.connect_btn.setObjectName("connect_btn")
        self.horizontalLayout.addWidget(self.connect_btn)
        self.combo_btn = MPushButton(listItem_Main)
        self.combo_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.combo_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.combo_btn.setText("")
        self.combo_btn.setObjectName("combo_btn")
        self.horizontalLayout.addWidget(self.combo_btn)
        self.targtName_le = MLineEdit(listItem_Main)
        self.targtName_le.setEnabled(False)
        self.targtName_le.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.targtName_le.setFont(font)
        self.targtName_le.setObjectName("targtName_le")
        self.horizontalLayout.addWidget(self.targtName_le)

        self.retranslateUi(listItem_Main)
        QtCore.QMetaObject.connectSlotsByName(listItem_Main)

    def retranslateUi(self, listItem_Main):
        _translate = QtCore.QCoreApplication.translate
        listItem_Main.setWindowTitle(_translate("listItem_Main", "Form"))
from dayu_widgets.line_edit import MLineEdit
from dayu_widgets.push_button import MPushButton
