# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Code\Faith_Proj\Faith\Tools\BS_Manager\UI\MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(377, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainLay = QtWidgets.QVBoxLayout()
        self.mainLay.setObjectName("mainLay")
        self.verticalLayout_2.addLayout(self.mainLay)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 377, 23))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actiontest = QtWidgets.QAction(MainWindow)
        self.actiontest.setObjectName("actiontest")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_BlendShape = QtWidgets.QAction(MainWindow)
        self.action_BlendShape.setObjectName("action_BlendShape")
        self.menuEdit.addAction(self.actiontest)
        self.menuEdit.addAction(self.action_BlendShape)
        self.menuSettings.addAction(self.action)
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuEdit.setTitle(_translate("MainWindow", "编辑"))
        self.menuSettings.setTitle(_translate("MainWindow", "工具"))
        self.actiontest.setText(_translate("MainWindow", "导出BlendShape"))
        self.action.setText(_translate("MainWindow", "镜像配置"))
        self.action_BlendShape.setText(_translate("MainWindow", "导入BlendShape"))
