# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_item_main(object):
    def setupUi(self, item_main):
        item_main.setObjectName("item_main")
        item_main.resize(304, 43)
        self.horizontalLayout = QtWidgets.QHBoxLayout(item_main)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.val_lb = MLabel()
        self.val_lb.setMinimumSize(QtCore.QSize(25, 25))
        self.val_lb.setMaximumSize(QtCore.QSize(25, 25))
        self.val_lb.setObjectName("val_lb")
        self.horizontalLayout.addWidget(self.val_lb)
        self.connect_btn = MPushButton()
        self.connect_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.connect_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.connect_btn.setStyleSheet("")
        self.connect_btn.setText("")
        self.connect_btn.setObjectName("connect_btn")
        self.horizontalLayout.addWidget(self.connect_btn)
        self.combo_btn = MPushButton()
        self.combo_btn.setMinimumSize(QtCore.QSize(25, 25))
        self.combo_btn.setMaximumSize(QtCore.QSize(25, 25))
        self.combo_btn.setText("")
        self.combo_btn.setObjectName("combo_btn")
        self.horizontalLayout.addWidget(self.combo_btn)
        self.targtName_le = MLineEdit()
        self.targtName_le.setObjectName("targtName_le")
        self.horizontalLayout.addWidget(self.targtName_le)

        self.retranslateUi(item_main)
        QtCore.QMetaObject.connectSlotsByName(item_main)

    def retranslateUi(self, item_main):
        _translate = QtCore.QCoreApplication.translate
        item_main.setWindowTitle(_translate("item_main", "Form"))
        self.val_lb.setText(_translate("item_main", "0.0"))
from dayu_widgets.label import MLabel
from dayu_widgets.line_edit import MLineEdit
from dayu_widgets.push_button import MPushButton
