# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\autoSkinWeight.ui'
#
# Created: Fri Apr 17 18:24:23 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_autoSkinWeight_Window(object):
    def setupUi(self, autoSkinWeight_Window):
        autoSkinWeight_Window.setObjectName("autoSkinWeight_Window")
        autoSkinWeight_Window.setEnabled(True)
        autoSkinWeight_Window.resize(209, 247)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(autoSkinWeight_Window.sizePolicy().hasHeightForWidth())
        autoSkinWeight_Window.setSizePolicy(sizePolicy)
        autoSkinWeight_Window.setCursor(QtCore.Qt.ArrowCursor)
        autoSkinWeight_Window.setLayoutDirection(QtCore.Qt.LeftToRight)
        autoSkinWeight_Window.setIconSize(QtCore.QSize(24, 24))
        autoSkinWeight_Window.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        autoSkinWeight_Window.setDocumentMode(False)
        autoSkinWeight_Window.setTabShape(QtWidgets.QTabWidget.Rounded)
        autoSkinWeight_Window.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(autoSkinWeight_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.geometryVtx_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.geometryVtx_lineEdit.setText("")
        self.geometryVtx_lineEdit.setObjectName("geometryVtx_lineEdit")
        self.gridLayout.addWidget(self.geometryVtx_lineEdit, 4, 0, 1, 2)
        self.joint_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.joint_pushButton.setObjectName("joint_pushButton")
        self.gridLayout.addWidget(self.joint_pushButton, 5, 2, 1, 2)
        self.nurbs_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.nurbs_pushButton.setEnabled(True)
        self.nurbs_pushButton.setObjectName("nurbs_pushButton")
        self.gridLayout.addWidget(self.nurbs_pushButton, 6, 2, 1, 2)
        self.joint_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.joint_lineEdit.setText("")
        self.joint_lineEdit.setObjectName("joint_lineEdit")
        self.gridLayout.addWidget(self.joint_lineEdit, 5, 0, 1, 2)
        self.apply_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.apply_pushButton.setObjectName("apply_pushButton")
        self.gridLayout.addWidget(self.apply_pushButton, 10, 0, 3, 4)
        self.nurbs_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nurbs_lineEdit.setEnabled(True)
        self.nurbs_lineEdit.setText("")
        self.nurbs_lineEdit.setObjectName("nurbs_lineEdit")
        self.gridLayout.addWidget(self.nurbs_lineEdit, 6, 0, 1, 2)
        self.geometryVtx_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.geometryVtx_pushButton.setObjectName("geometryVtx_pushButton")
        self.gridLayout.addWidget(self.geometryVtx_pushButton, 4, 2, 1, 2)
        self.QProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.QProgressBar.setEnabled(True)
        self.QProgressBar.setProperty("value", 0)
        self.QProgressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.QProgressBar.setTextVisible(True)
        self.QProgressBar.setInvertedAppearance(False)
        self.QProgressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.QProgressBar.setObjectName("QProgressBar")
        self.gridLayout.addWidget(self.QProgressBar, 13, 0, 1, 4)
        self.startExpand_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.startExpand_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.startExpand_doubleSpinBox.setPrefix("")
        self.startExpand_doubleSpinBox.setMinimum(-200.0)
        self.startExpand_doubleSpinBox.setMaximum(200.0)
        self.startExpand_doubleSpinBox.setObjectName("startExpand_doubleSpinBox")
        self.gridLayout.addWidget(self.startExpand_doubleSpinBox, 7, 2, 2, 2)
        self.endExpand_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.endExpand_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.endExpand_doubleSpinBox.setPrefix("")
        self.endExpand_doubleSpinBox.setMinimum(-200.0)
        self.endExpand_doubleSpinBox.setMaximum(200.0)
        self.endExpand_doubleSpinBox.setObjectName("endExpand_doubleSpinBox")
        self.gridLayout.addWidget(self.endExpand_doubleSpinBox, 9, 2, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 0, 2, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 9, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.calculation_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.calculation_comboBox.setObjectName("calculation_comboBox")
        self.calculation_comboBox.addItem("")
        self.calculation_comboBox.addItem("")
        self.gridLayout.addWidget(self.calculation_comboBox, 2, 2, 1, 2)
        self.hide = QtWidgets.QWidget(self.centralwidget)
        self.hide.setEnabled(False)
        self.hide.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.hide.setObjectName("hide")
        self.startExpand_convert = QtWidgets.QLineEdit(self.hide)
        self.startExpand_convert.setGeometry(QtCore.QRect(10, 30, 133, 20))
        self.startExpand_convert.setObjectName("startExpand_convert")
        self.endExpand_convert = QtWidgets.QLineEdit(self.hide)
        self.endExpand_convert.setGeometry(QtCore.QRect(10, 10, 133, 20))
        self.endExpand_convert.setObjectName("endExpand_convert")
        self.gridLayout.addWidget(self.hide, 14, 1, 1, 2)
        self.algorithm_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.algorithm_comboBox.setObjectName("algorithm_comboBox")
        self.algorithm_comboBox.addItem("")
        self.algorithm_comboBox.addItem("")
        self.algorithm_comboBox.addItem("")
        self.algorithm_comboBox.addItem("")
        self.algorithm_comboBox.addItem("")
        self.gridLayout.addWidget(self.algorithm_comboBox, 3, 2, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        autoSkinWeight_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(autoSkinWeight_Window)
        self.statusbar.setEnabled(False)
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        autoSkinWeight_Window.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(autoSkinWeight_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 209, 23))
        self.menubar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menubar.setObjectName("menubar")
        autoSkinWeight_Window.setMenuBar(self.menubar)

        self.retranslateUi(autoSkinWeight_Window)
        QtCore.QObject.connect(self.startExpand_doubleSpinBox, QtCore.SIGNAL("valueChanged(QString)"), self.startExpand_convert.setText)
        QtCore.QObject.connect(self.endExpand_doubleSpinBox, QtCore.SIGNAL("valueChanged(QString)"), self.endExpand_convert.setText)
        QtCore.QMetaObject.connectSlotsByName(autoSkinWeight_Window)

    def retranslateUi(self, autoSkinWeight_Window):
        autoSkinWeight_Window.setWindowTitle(QtWidgets.QApplication.translate("autoSkinWeight_Window", "autoSkinWeight", None, -1))
        self.geometryVtx_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("autoSkinWeight_Window", "geometryVtx", None, -1))
        self.joint_pushButton.setText(QtWidgets.QApplication.translate("autoSkinWeight_Window", "Load", None, -1))
        self.joint_pushButton.setProperty("+command", QtWidgets.QApplication.translate("autoSkinWeight_Window", "autoWeightClass.use.joint_pushButton_cmd", None, -1))
        self.nurbs_pushButton.setText(QtWidgets.QApplication.translate("autoSkinWeight_Window", "Load", None, -1))
        self.nurbs_pushButton.setProperty("+command", QtWidgets.QApplication.translate("autoSkinWeight_Window", "autoWeightClass.use.nurbs_pushButton_cmd", None, -1))
        self.joint_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("autoSkinWeight_Window", "joint", None, -1))
        self.apply_pushButton.setText(QtWidgets.QApplication.translate("autoSkinWeight_Window", "Apply", None, -1))
        self.apply_pushButton.setProperty("+command", QtWidgets.QApplication.translate("autoSkinWeight_Window", "autoWeightClass.use.apply_pushButton_cmd", None, -1))
        self.nurbs_lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("autoSkinWeight_Window", "nurbsSurface", None, -1))
        self.geometryVtx_pushButton.setText(QtWidgets.QApplication.translate("autoSkinWeight_Window", "Load", None, -1))
        self.geometryVtx_pushButton.setProperty("+command", QtWidgets.QApplication.translate("autoSkinWeight_Window", "autoWeightClass.use.geometryVtx_pushButton_cmd", None, -1))
        self.QProgressBar.setFormat(QtWidgets.QApplication.translate("autoSkinWeight_Window", "%p%", None, -1))
        self.startExpand_doubleSpinBox.setSuffix(QtWidgets.QApplication.translate("autoSkinWeight_Window", "%", None, -1))
        self.endExpand_doubleSpinBox.setSuffix(QtWidgets.QApplication.translate("autoSkinWeight_Window", "%", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("autoSkinWeight_Window", "startExpand:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("autoSkinWeight_Window", "endExpand:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("autoSkinWeight_Window", "algorithm:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("autoSkinWeight_Window", "calculation pattern:", None, -1))
        self.calculation_comboBox.setItemText(0, QtWidgets.QApplication.translate("autoSkinWeight_Window", "distance", None, -1))
        self.calculation_comboBox.setItemText(1, QtWidgets.QApplication.translate("autoSkinWeight_Window", "nurbs", None, -1))
        self.startExpand_convert.setText(QtWidgets.QApplication.translate("autoSkinWeight_Window", "0.00%", None, -1))
        self.endExpand_convert.setText(QtWidgets.QApplication.translate("autoSkinWeight_Window", "0.00%", None, -1))
        self.algorithm_comboBox.setItemText(0, QtWidgets.QApplication.translate("autoSkinWeight_Window", "linear", None, -1))
        self.algorithm_comboBox.setItemText(1, QtWidgets.QApplication.translate("autoSkinWeight_Window", "smooth", None, -1))
        self.algorithm_comboBox.setItemText(2, QtWidgets.QApplication.translate("autoSkinWeight_Window", "after", None, -1))
        self.algorithm_comboBox.setItemText(3, QtWidgets.QApplication.translate("autoSkinWeight_Window", "before", None, -1))
        self.algorithm_comboBox.setItemText(4, QtWidgets.QApplication.translate("autoSkinWeight_Window", "formula", None, -1))

