# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(325, 488)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Content = QtWidgets.QFrame(Form)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Main_frame = QtWidgets.QFrame(self.Content)
        self.Main_frame.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_frame.setObjectName("Main_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Main_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.node_hb = QtWidgets.QHBoxLayout()
        self.node_hb.setContentsMargins(0, 0, 0, -1)
        self.node_hb.setObjectName("node_hb")
        self.node_btn = QtWidgets.QPushButton(self.Main_frame)
        self.node_btn.setEnabled(True)
        self.node_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.node_btn.setFont(font)
        self.node_btn.setStyleSheet("QPushButton {    \n"
"    color: rgb(255, 255, 255);\n"
"    background-image: url(:/16x16/16x16/cil-hand-point-right.png);\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 25px;\n"
"}\n"
"")
        self.node_btn.setObjectName("node_btn")
        self.node_hb.addWidget(self.node_btn)
        self.node_le = QtWidgets.QLineEdit(self.Main_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.node_le.setFont(font)
        self.node_le.setStyleSheet("QLineEdit\n"
"{\n"
"border: 1px solid gray;\n"
"border-radius: 4px;\n"
"\n"
"background: gray;\n"
"selection-background-color: darkgray;\n"
"}")
        self.node_le.setReadOnly(True)
        self.node_le.setObjectName("node_le")
        self.node_hb.addWidget(self.node_le)
        self.load_btn = QtWidgets.QPushButton(self.Main_frame)
        self.load_btn.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.load_btn.setFont(font)
        self.load_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border-radius:3px;\n"
"    background-color: rgb(125, 129, 162);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.load_btn.setObjectName("load_btn")
        self.node_hb.addWidget(self.load_btn)
        self.verticalLayout_3.addLayout(self.node_hb)
        self.direc_hb = QtWidgets.QHBoxLayout()
        self.direc_hb.setObjectName("direc_hb")
        self.direction_btn = QtWidgets.QPushButton(self.Main_frame)
        self.direction_btn.setEnabled(False)
        self.direction_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.direction_btn.setFont(font)
        self.direction_btn.setStyleSheet("QPushButton {    \n"
"    color: rgb(255, 255, 255);\n"
"    background-position: left center;\n"
"    background-image: url(:/16x16/16x16/cil-featured-playlist.png);\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding-left: 25px;\n"
"}\n"
"")
        self.direction_btn.setObjectName("direction_btn")
        self.direc_hb.addWidget(self.direction_btn)
        self.frnt_rbtn = QtWidgets.QRadioButton(self.Main_frame)
        self.frnt_rbtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frnt_rbtn.setFont(font)
        self.frnt_rbtn.setStyleSheet("color: rgb(255, 255, 255);")
        self.frnt_rbtn.setChecked(True)
        self.frnt_rbtn.setObjectName("frnt_rbtn")
        self.direc_hb.addWidget(self.frnt_rbtn)
        self.after_rbtn = QtWidgets.QRadioButton(self.Main_frame)
        self.after_rbtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        self.after_rbtn.setFont(font)
        self.after_rbtn.setStyleSheet("color: rgb(255, 255, 255);")
        self.after_rbtn.setObjectName("after_rbtn")
        self.direc_hb.addWidget(self.after_rbtn)
        self.verticalLayout_3.addLayout(self.direc_hb)
        self.list_mainvb = QtWidgets.QVBoxLayout()
        self.list_mainvb.setObjectName("list_mainvb")
        self.listVb = QtWidgets.QVBoxLayout()
        self.listVb.setObjectName("listVb")
        self.driver_vb = QtWidgets.QVBoxLayout()
        self.driver_vb.setObjectName("driver_vb")
        self.driver_lb = QtWidgets.QLabel(self.Main_frame)
        self.driver_lb.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        self.driver_lb.setFont(font)
        self.driver_lb.setStyleSheet("color: rgb(255, 255, 255);")
        self.driver_lb.setObjectName("driver_lb")
        self.driver_vb.addWidget(self.driver_lb)
        self.driver_list = DragQListView(self.Main_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.driver_list.setFont(font)
        self.driver_list.setObjectName("driver_list")
        self.driver_vb.addWidget(self.driver_list)
        self.listVb.addLayout(self.driver_vb)
        self.driven_lb = QtWidgets.QLabel(self.Main_frame)
        self.driven_lb.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        self.driven_lb.setFont(font)
        self.driven_lb.setStyleSheet("color: rgb(255, 255, 255);")
        self.driven_lb.setObjectName("driven_lb")
        self.listVb.addWidget(self.driven_lb)
        self.driven_list = DragQListView(self.Main_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.driven_list.setFont(font)
        self.driven_list.setObjectName("driven_list")
        self.listVb.addWidget(self.driven_list)
        self.bottomBtn_hb = QtWidgets.QHBoxLayout()
        self.bottomBtn_hb.setObjectName("bottomBtn_hb")
        self.refresh_btn = QtWidgets.QPushButton(self.Main_frame)
        self.refresh_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.refresh_btn.setFont(font)
        self.refresh_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border-radius:8px;\n"
"    background-color: rgb(125, 129, 162);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.refresh_btn.setObjectName("refresh_btn")
        self.bottomBtn_hb.addWidget(self.refresh_btn)
        self.mirror_btn = QtWidgets.QPushButton(self.Main_frame)
        self.mirror_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.mirror_btn.setFont(font)
        self.mirror_btn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border-radius:8px;\n"
"    background-color: rgb(125, 129, 162);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 170, 255);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.mirror_btn.setObjectName("mirror_btn")
        self.bottomBtn_hb.addWidget(self.mirror_btn)
        self.listVb.addLayout(self.bottomBtn_hb)
        self.list_mainvb.addLayout(self.listVb)
        self.verticalLayout_3.addLayout(self.list_mainvb)
        self.horizontalLayout_2.addWidget(self.Main_frame)
        self.verticalLayout.addWidget(self.Content)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SDK_TOOL v0.0.1"))
        self.node_btn.setText(_translate("Form", "Node"))
        self.node_le.setPlaceholderText(_translate("Form", "Please select one node."))
        self.load_btn.setText(_translate("Form", ">> L o a d"))
        self.direction_btn.setText(_translate("Form", "Direction"))
        self.frnt_rbtn.setText(_translate("Form", "F r o n t"))
        self.after_rbtn.setText(_translate("Form", "A f t e r"))
        self.driver_lb.setText(_translate("Form", "Driver:"))
        self.driven_lb.setText(_translate("Form", "Driven:"))
        self.refresh_btn.setText(_translate("Form", "Refresh"))
        self.mirror_btn.setText(_translate("Form", "Mirror"))
from Faith.Core.aboutUI import DragQListView
from Faith.Tools.SDK_Manager.UI import icon_rc
