# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Code\Faith_Proj\Faith\Tools\TestUI\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tab_main(object):
    def setupUi(self, tab_main):
        tab_main.setObjectName("tab_main")
        tab_main.resize(322, 641)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(tab_main)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(tab_main)
        self.widget.setStyleSheet("QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }")
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 270, 504))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.load_hb = QtWidgets.QHBoxLayout()
        self.load_hb.setObjectName("load_hb")
        self.load_btn = MPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.load_btn.setFont(font)
        self.load_btn.setObjectName("load_btn")
        self.load_hb.addWidget(self.load_btn)
        self.load_le = MLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.load_le.setFont(font)
        self.load_le.setObjectName("load_le")
        self.load_hb.addWidget(self.load_le)
        self.setting_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.setting_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.setting_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.setting_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_preferences_150.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_preferences_150_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_preferences_150_light.png);\n"
"}")
        self.setting_btn.setText("")
        self.setting_btn.setObjectName("setting_btn")
        self.load_hb.addWidget(self.setting_btn)
        self.verticalLayout_5.addLayout(self.load_hb)
        self.bs_hb = QtWidgets.QHBoxLayout()
        self.bs_hb.setObjectName("bs_hb")
        self.bs_lb = MLabel(self.scrollAreaWidgetContents)
        self.bs_lb.setMinimumSize(QtCore.QSize(0, 0))
        self.bs_lb.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.bs_lb.setFont(font)
        self.bs_lb.setObjectName("bs_lb")
        self.bs_hb.addWidget(self.bs_lb)
        self.bs_cb = MComboBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.bs_cb.setFont(font)
        self.bs_cb.setObjectName("bs_cb")
        self.bs_cb.addItem("")
        self.bs_hb.addWidget(self.bs_cb)
        self.verticalLayout_5.addLayout(self.bs_hb)
        self.target_lb = MLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.target_lb.setFont(font)
        self.target_lb.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.target_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.target_lb.setObjectName("target_lb")
        self.verticalLayout_5.addWidget(self.target_lb)
        self.search_le = MLineEdit(self.scrollAreaWidgetContents)
        self.search_le.setObjectName("search_le")
        self.verticalLayout_5.addWidget(self.search_le)
        self.target_list = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.target_list.setMinimumSize(QtCore.QSize(0, 300))
        self.target_list.setObjectName("target_list")
        self.verticalLayout_5.addWidget(self.target_list)
        self.edit_hb = QtWidgets.QHBoxLayout()
        self.edit_hb.setSpacing(2)
        self.edit_hb.setObjectName("edit_hb")
        self.edit_btn = MPushButton(self.scrollAreaWidgetContents)
        self.edit_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.edit_btn.setFont(font)
        self.edit_btn.setStyleSheet("")
        self.edit_btn.setObjectName("edit_btn")
        self.edit_hb.addWidget(self.edit_btn)
        spacerItem = QtWidgets.QSpacerItem(80, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.edit_hb.addItem(spacerItem)
        self.ccs_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.ccs_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.ccs_btn.setMaximumSize(QtCore.QSize(10, 20))
        self.ccs_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_comboMembers_200.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_comboMembers_200_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_comboMembers_200_light.png);\n"
"}")
        self.ccs_btn.setText("")
        self.ccs_btn.setObjectName("ccs_btn")
        self.edit_hb.addWidget(self.ccs_btn)
        self.dup_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.dup_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.dup_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.dup_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_weightPaste_200.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_weightPaste_200_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_weightPaste_200_light.png);\n"
"}")
        self.dup_btn.setText("")
        self.dup_btn.setObjectName("dup_btn")
        self.edit_hb.addWidget(self.dup_btn)
        self.extr_btn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.extr_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.extr_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.extr_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_weightExport_200.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_weightExport_200_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_weightExport_200_light.png);\n"
"}")
        self.extr_btn.setText("")
        self.extr_btn.setObjectName("extr_btn")
        self.edit_hb.addWidget(self.extr_btn)
        self.verticalLayout_5.addLayout(self.edit_hb)
        self.inbetween_list = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.inbetween_list.setMaximumSize(QtCore.QSize(16777215, 40))
        self.inbetween_list.setObjectName("inbetween_list")
        self.verticalLayout_5.addWidget(self.inbetween_list)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.verticalLayout_3.addWidget(self.widget)
        self.mirror_widget = QtWidgets.QWidget(tab_main)
        self.mirror_widget.setObjectName("mirror_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mirror_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.axis_hb = QtWidgets.QHBoxLayout()
        self.axis_hb.setObjectName("axis_hb")
        self.axis_lb = MLabel(self.mirror_widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.axis_lb.setFont(font)
        self.axis_lb.setObjectName("axis_lb")
        self.axis_hb.addWidget(self.axis_lb)
        self.x_rb = MRadioButton(self.mirror_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.x_rb.setFont(font)
        self.x_rb.setObjectName("x_rb")
        self.axis_hb.addWidget(self.x_rb)
        self.y_rb = MRadioButton(self.mirror_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.y_rb.setFont(font)
        self.y_rb.setChecked(True)
        self.y_rb.setObjectName("y_rb")
        self.axis_hb.addWidget(self.y_rb)
        self.z_rb = MRadioButton(self.mirror_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.z_rb.setFont(font)
        self.z_rb.setObjectName("z_rb")
        self.axis_hb.addWidget(self.z_rb)
        self.verticalLayout_2.addLayout(self.axis_hb)
        self.name_hb = QtWidgets.QHBoxLayout()
        self.name_hb.setObjectName("name_hb")
        self.name_lb = MLabel(self.mirror_widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.name_lb.setFont(font)
        self.name_lb.setObjectName("name_lb")
        self.name_hb.addWidget(self.name_lb)
        self.name_le = MLineEdit(self.mirror_widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.name_le.setFont(font)
        self.name_le.setObjectName("name_le")
        self.name_hb.addWidget(self.name_le)
        self.verticalLayout_2.addLayout(self.name_hb)
        self.mirror_tgt_btn = MPushButton(self.mirror_widget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.mirror_tgt_btn.setFont(font)
        self.mirror_tgt_btn.setObjectName("mirror_tgt_btn")
        self.verticalLayout_2.addWidget(self.mirror_tgt_btn)
        self.verticalLayout_3.addWidget(self.mirror_widget)
        self.drive_sidget = QtWidgets.QWidget(tab_main)
        self.drive_sidget.setObjectName("drive_sidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drive_sidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.driver_hb = QtWidgets.QHBoxLayout()
        self.driver_hb.setObjectName("driver_hb")
        self.driver_lb = MLabel(self.drive_sidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.driver_lb.setFont(font)
        self.driver_lb.setObjectName("driver_lb")
        self.driver_hb.addWidget(self.driver_lb)
        self.driver_le = QtWidgets.QLineEdit(self.drive_sidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.driver_le.setFont(font)
        self.driver_le.setObjectName("driver_le")
        self.driver_hb.addWidget(self.driver_le)
        self.driver_btn = QtWidgets.QPushButton(self.drive_sidget)
        self.driver_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.driver_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.driver_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_select_150.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_select_150_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_select_150_light.png);\n"
"}")
        self.driver_btn.setText("")
        self.driver_btn.setObjectName("driver_btn")
        self.driver_hb.addWidget(self.driver_btn)
        self.verticalLayout.addLayout(self.driver_hb)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.attr_lb = MLabel(self.drive_sidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.attr_lb.setFont(font)
        self.attr_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.attr_lb.setObjectName("attr_lb")
        self.horizontalLayout.addWidget(self.attr_lb)
        self.attr_combo = MComboBox(self.drive_sidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.attr_combo.setFont(font)
        self.attr_combo.setObjectName("attr_combo")
        self.attr_combo.addItem("")
        self.horizontalLayout.addWidget(self.attr_combo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.time_hb = QtWidgets.QHBoxLayout()
        self.time_hb.setObjectName("time_hb")
        self.time_lb = MLabel(self.drive_sidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.time_lb.setFont(font)
        self.time_lb.setObjectName("time_lb")
        self.time_hb.addWidget(self.time_lb)
        self.startAdd_btn = QtWidgets.QPushButton(self.drive_sidget)
        self.startAdd_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.startAdd_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.startAdd_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_btn_locator_150.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_btn_locator_150_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_btn_locator_150_light.png);\n"
"}")
        self.startAdd_btn.setText("")
        self.startAdd_btn.setObjectName("startAdd_btn")
        self.time_hb.addWidget(self.startAdd_btn)
        self.start_spin = MSpinBox(self.drive_sidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.start_spin.setFont(font)
        self.start_spin.setObjectName("start_spin")
        self.time_hb.addWidget(self.start_spin)
        self.endAdd_btn = QtWidgets.QPushButton(self.drive_sidget)
        self.endAdd_btn.setMinimumSize(QtCore.QSize(20, 20))
        self.endAdd_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.endAdd_btn.setStyleSheet("QPushButton{\n"
"border-image: url(:/icon/SHAPES_btn_locator_150.png);\n"
"}\n"
"QPushButton:hover{\n"
"border-image: url(:/icon/SHAPES_btn_locator_150_light.png);\n"
"}\n"
"QPushButton:pressed{\n"
"border-image: url(:/icon/SHAPES_btn_locator_150_light.png);\n"
"}")
        self.endAdd_btn.setText("")
        self.endAdd_btn.setObjectName("endAdd_btn")
        self.time_hb.addWidget(self.endAdd_btn)
        self.end_spin = MSpinBox(self.drive_sidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.end_spin.setFont(font)
        self.end_spin.setObjectName("end_spin")
        self.time_hb.addWidget(self.end_spin)
        self.verticalLayout.addLayout(self.time_hb)
        self.type_hb = QtWidgets.QHBoxLayout()
        self.type_hb.setObjectName("type_hb")
        self.type_lb = MLabel(self.drive_sidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.type_lb.setFont(font)
        self.type_lb.setObjectName("type_lb")
        self.type_hb.addWidget(self.type_lb)
        self.type_combo = MComboBox(self.drive_sidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.type_combo.setFont(font)
        self.type_combo.setObjectName("type_combo")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_combo.addItem("")
        self.type_hb.addWidget(self.type_combo)
        self.infi_lb = QtWidgets.QLabel(self.drive_sidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.infi_lb.setFont(font)
        self.infi_lb.setObjectName("infi_lb")
        self.type_hb.addWidget(self.infi_lb)
        self.infi_combo = MComboBox(self.drive_sidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.infi_combo.setFont(font)
        self.infi_combo.setObjectName("infi_combo")
        self.infi_combo.addItem("")
        self.infi_combo.addItem("")
        self.infi_combo.addItem("")
        self.infi_combo.addItem("")
        self.type_hb.addWidget(self.infi_combo)
        self.verticalLayout.addLayout(self.type_hb)
        self.create_hb = QtWidgets.QHBoxLayout()
        self.create_hb.setObjectName("create_hb")
        self.apply_btn = MPushButton(self.drive_sidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.apply_btn.setFont(font)
        self.apply_btn.setObjectName("apply_btn")
        self.create_hb.addWidget(self.apply_btn)
        self.mirror_btn = MPushButton(self.drive_sidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.mirror_btn.setFont(font)
        self.mirror_btn.setObjectName("mirror_btn")
        self.create_hb.addWidget(self.mirror_btn)
        self.verticalLayout.addLayout(self.create_hb)
        self.verticalLayout_3.addWidget(self.drive_sidget)

        self.retranslateUi(tab_main)
        QtCore.QMetaObject.connectSlotsByName(tab_main)

    def retranslateUi(self, tab_main):
        _translate = QtCore.QCoreApplication.translate
        tab_main.setWindowTitle(_translate("tab_main", "Form"))
        self.load_btn.setToolTip(_translate("tab_main", "Load mesh"))
        self.load_btn.setText(_translate("tab_main", "Load"))
        self.load_le.setPlaceholderText(_translate("tab_main", "Load one mesh with BS"))
        self.setting_btn.setToolTip(_translate("tab_main", "Settings"))
        self.bs_lb.setText(_translate("tab_main", "BS Name"))
        self.bs_cb.setItemText(0, _translate("tab_main", "None"))
        self.target_lb.setText(_translate("tab_main", "BlendShape Target List "))
        self.edit_btn.setToolTip(_translate("tab_main", "Crate new blendShape"))
        self.edit_btn.setText(_translate("tab_main", "Create Target"))
        self.ccs_btn.setToolTip(_translate("tab_main", "Create Correct Shape"))
        self.dup_btn.setToolTip(_translate("tab_main", "Duplicate mesh"))
        self.extr_btn.setToolTip(_translate("tab_main", "Extract target"))
        self.axis_lb.setText(_translate("tab_main", "Axis"))
        self.x_rb.setText(_translate("tab_main", "X"))
        self.y_rb.setText(_translate("tab_main", "Y"))
        self.z_rb.setText(_translate("tab_main", "Z"))
        self.name_lb.setText(_translate("tab_main", "Name Of Copy"))
        self.name_le.setPlaceholderText(_translate("tab_main", "Mirror Name Of Shape"))
        self.mirror_tgt_btn.setText(_translate("tab_main", "Mirror Target"))
        self.driver_lb.setText(_translate("tab_main", "Driver"))
        self.driver_le.setPlaceholderText(_translate("tab_main", "Select one driver attribute."))
        self.attr_lb.setText(_translate("tab_main", "Attribute"))
        self.attr_combo.setItemText(0, _translate("tab_main", "None"))
        self.time_lb.setText(_translate("tab_main", "Start/End"))
        self.type_lb.setText(_translate("tab_main", "Type"))
        self.type_combo.setItemText(0, _translate("tab_main", "Linear"))
        self.type_combo.setItemText(1, _translate("tab_main", "Slow"))
        self.type_combo.setItemText(2, _translate("tab_main", "Fast"))
        self.type_combo.setItemText(3, _translate("tab_main", "Smooth"))
        self.infi_lb.setText(_translate("tab_main", "Infinity"))
        self.infi_combo.setItemText(0, _translate("tab_main", "None"))
        self.infi_combo.setItemText(1, _translate("tab_main", "Post"))
        self.infi_combo.setItemText(2, _translate("tab_main", "Pre"))
        self.infi_combo.setItemText(3, _translate("tab_main", "Pre/Post"))
        self.apply_btn.setText(_translate("tab_main", "Apply"))
        self.mirror_btn.setText(_translate("tab_main", "Mirror"))
from dayu_widgets.combo_box import MComboBox
from dayu_widgets.label import MLabel
from dayu_widgets.line_edit import MLineEdit
from dayu_widgets.push_button import MPushButton
from dayu_widgets.radio_button import MRadioButton
from dayu_widgets.spin_box import MSpinBox
import icon_rc
